[package]
name = "tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", features = ["rayon"] }
glam = "0.30"
rand = "0.9"
rayon = "1.10"
anyhow = "1.0"
tobj = "4.0"

# [profile.release]
# debug = true
